name: Build macOS App

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --name "UK_Uchet_Mac" --noconfirm --clean --windowed --add-data "app/templates:app/templates" --add-data "app_icon.png:." app/main.py

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UK_Uchet_Mac
        path: dist/UK_Uchet_Mac.app
